spring:
  application:
    name: atp-server
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  messages:
    basename: messages, messages-network-and-error-handler
    encoding: UTF-8
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  graphql:
    graphiql:
      enabled: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: ASSIGN_UUID
      # 全局逻辑删除的实体字段名
      logic-delete-field: deleted
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true
    default-enum-type-handler: com.soulcraft.mybatis.common.handler.AutoEnumTypeHandler

server:
  port: 3170
graphql:
  servlet:
    exception-handlers-enabled: true
  graphiql:
    enabled: true

logging:
  level:
    root: info
    io.micrometer.core.instrument.logging.*: DEBUG

infra:
  auth:
    # 支持的登录方式
    allowedAuthProviders: EMAIL
    # 登录Token的复杂度
    tokenSaltComplexity: 10
    # 登录Token的复杂度
    tokenLength: 25
    # 登录Token的有效期，单位：小时
    loginLinkTokenValidity: 3
    # 登录链接前缀
    loginLinkPrefix: http://localhost:3000/enter?token=
    # 用户默认密码
    defaultPassword: Atp@123

jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT开头
  tokenHead: 'Bearer '
  # JWT加解密使用的密钥
  secret: atp-secret
  # JWT的超期限时间(60*60)
  access_token_expiration: 3600
  # JWT的超期限时间(60*60*24*7)
  refresh_token_expiration: 604800

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui/**
      - /swagger-resources/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /graphiql
      - /graphql
#      - /websocket
#      - /subscriptions
      - /ping
      - /v1/auth/providers
      - /v1/auth/signIn
      - /v1/auth/verify
      - /v1/auth/logout
      - /error

email:
  # email 校验的正则表达式
  validatePattern: ^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$
  # smtp服务配置
  smtp:
    host: smtp.126.com
    port: 25
    needsValidate: true
  # 邮件发送者配置
  sender:
    email: zhoutao10518@126.com
    password: PNRMFWRNIWAKKVVX
    # 邮件显示的发送者
    name: Atp
  templates:
    userInvitation:
      fileName: user-invitation.html
      subject: 用户注册/登录邮件