version: '3.7'
services:
  mysql_8022:
    image: mysql:8.0.22
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
    restart: always
    container_name: mysql_8022
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root@2024
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    command:
      --sql_mode=""
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    ports:
      - "3306:3306"
    volumes:
      - ../data/mysql_data:/var/lib/mysql
      - ./mysql/:/docker-entrypoint-initdb.d/
    networks:
      - atp
networks:
  atp:
    external: true
